# All About NumPy

In [1]:
import numpy as np

In [2]:
list1=[2,6,5,3,1]
array1=np.array(list1,dtype="int")

In [3]:
print(array1)
print(type(array1))
print(array1[2])

[2 6 5 3 1]
<class 'numpy.ndarray'>
5


In [4]:
array3=np.arange(1,8)
print(array3)

[1 2 3 4 5 6 7]


In [5]:
array4=np.arange(11,17).reshape(2,3)
print(array4)

[[11 12 13]
 [14 15 16]]


In [6]:
array5=np.zeros(5)
print(array5)

[0. 0. 0. 0. 0.]


In [7]:
array6=np.zeros((3,5))
print(array6)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
array7=np.ones(3)
print(array7)

[1. 1. 1.]


In [9]:
# Attributes of Array
list2=[[10,20,30],[40,50,60],[70,80,90]]
array2=np.array(list2)
print(array2)
print(type(array2))
print(array2.ndim)
print(array2.size)
print(array2.shape)
print(array2.itemsize)
print(array2.dtype)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
<class 'numpy.ndarray'>
2
9
(3, 3)
4
int32


In [10]:
array=np.array([[[1,2,3],[5,6,4]],[[10,12,11],[6,9,3]]])
print(array)
print(array.ndim)
print(array.shape)

[[[ 1  2  3]
  [ 5  6  4]]

 [[10 12 11]
  [ 6  9  3]]]
3
(2, 2, 3)


In [11]:
# Slicing in NumPy Arrays
array8=np.array([2,3,6,9,8,7,1])
print(array8[2])
print(array8[1:5])
print(array8[0:5:2])
print(array8[-1:-7:-2])
print(array8[::-1])
print(array8[:])
print(array8[::2])

6
[3 6 9 8]
[2 6 8]
[1 8 6]
[1 7 8 9 6 3 2]
[2 3 6 9 8 7 1]
[2 6 8 1]


# Arithmetic Operations on NumPy Arrays


Addition

In [12]:
x=np.array([2,6])
y=np.array([8,10])

z=x+y
print(z)

[10 16]


In [13]:
a=np.array([[2,3],
           [7,1]])
b=np.array([[5,8],
          [6,9]])
c=a+b
print(c)

[[ 7 11]
 [13 10]]


Substraction

In [14]:
a=np.array([[2,3],
           [7,1]])
b=np.array([[5,8],
          [6,9]])
c=a-b
print(c)

[[-3 -5]
 [ 1 -8]]


Multiplication

In [15]:
a=np.array([[2,3],
           [7,1]])
b=np.array([[5,8],
          [6,9]])
c=a*b
print(c)

[[10 24]
 [42  9]]


Matrix Multiplication

In [16]:
a=np.array([[2,3],
           [7,1]])
b=np.array([[5,8],
          [6,9]])
c=a@b
print(c)

[[28 43]
 [41 65]]


Division

In [17]:
a=np.array([[10,24],
           [48,27]])
b=np.array([[5,8],
          [6,9]])
c=a/b
print(c)

[[2. 3.]
 [8. 3.]]


Floor Division

In [18]:
a=np.array([[10,24],
           [48,27]])
b=np.array([[5,8],
          [6,9]])
c=a//b
print(c)

[[2 3]
 [8 3]]


Exponentiation

In [19]:
a=np.array([[2,3],
           [7,1]])
b=np.array([[5,3],
          [2,9]])
c=a**b
print(c)

[[32 27]
 [49  1]]


Modulo(%)

In [20]:
a=np.array([[2,10],
           [7,56]])
b=np.array([[5,5],
          [6,9]])
c=a%b
print(c)

[[2 0]
 [1 2]]


Transpose

In [21]:
a=np.array([[2,3],
           [7,1]])
b=np.array([[5,8],
          [6,9]])

print(a.transpose())
print(b.transpose())

[[2 7]
 [3 1]]
[[5 6]
 [8 9]]


# Sorting in 2D Arrays

In [26]:
# To Sort Row-wise  (By Default it sorts row-wise, you can also deliberately mention axis=1)
x=np.array([[2,3,6],
           [5,4,9],
           [7,1,2]])
y=np.sort(x)
print(y)

[[2 3 6]
 [4 5 9]
 [1 2 7]]


In [27]:
# To Sort Column-wise
x=np.array([[2,3,6],
           [5,4,9],
           [7,1,2]])
y=np.sort(x,axis=0)
print(y)

[[2 1 2]
 [5 3 6]
 [7 4 9]]


In [32]:
# argsort--->gives the Sorted Index Number
x=np.array([[2,3,6],
           [5,4,9],
           [7,1,2]])
y=np.argsort(x,axis=1)
print(y)

[[0 1 2]
 [1 0 2]
 [1 2 0]]


In [33]:
# argsort--->gives the Sorted Index Number
x=np.array([[2,3,6],
           [5,4,9],
           [7,1,2]])
y=np.argsort(x,axis=0)
print(y)

[[0 2 2]
 [1 0 0]
 [2 1 1]]


In [34]:
x=np.array([2,6,3,1,8,0,9])
print(np.sort(x))

[0 1 2 3 6 8 9]


In [35]:
x=np.array([2,6,3,1,8,0,9])
print(np.argsort(x))

[5 3 0 2 1 4 6]


# Statistical Operations On NumPy Arrays

In [51]:
x=np.array([5,3,6,9,8,2,0,7])
print(x)
print(np.mean(x))
print(np.max(x))
print(np.min(x))
print(np.sum(x))
print(np.median(x))
y=np.prod(x)   
print(y)
print(np.var(x))
print(np.std(x))

[5 3 6 9 8 2 0 7]
5.0
9
0
40
5.5
0
8.5
2.9154759474226504
