In [3]:
import numpy as np

Example 1

In [4]:
myarray=np.array([[3,6,12],[1,8,7],[10,11,19]])


In [5]:
myarray

array([[ 3,  6, 12],
       [ 1,  8,  7],
       [10, 11, 19]])

In [6]:
myarray[2,2]   #To find a particular number.

19

In [7]:
myarray.dtype #defines how bytes in memory will be interpreted by a scalar (i.e. a single number) or an array and the way in which the bytes will be treated.

dtype('int32')

In [8]:
myarray.shape  #Shows number of rows and columns

(3, 3)

In [9]:
myarray.size  #Number of elements in the array

9

2D Array Example

In [10]:
x=[[1,3,5],[2,4,6],[12,24,15]]

In [11]:
print(x)

[[1, 3, 5], [2, 4, 6], [12, 24, 15]]


In [12]:
ar=np.array(x)

In [13]:
ar

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [12, 24, 15]])

In [14]:
print(ar)

[[ 1  3  5]
 [ 2  4  6]
 [12 24 15]]


In [15]:
ar.sum(axis=0)  #calculates sum of columns

array([15, 31, 26])

In [16]:
ar.sum(axis=1)  #calcuates sum of rows

array([ 9, 12, 51])

In [17]:
 ar.T #Rows and Columns are interchanged.----->T is Transpose

array([[ 1,  2, 12],
       [ 3,  4, 24],
       [ 5,  6, 15]])

In [18]:
ar.flat

In [19]:
for i in ar.flat:
    print(i)

1
3
5
2
4
6
12
24
15


In [20]:
ar.ndim  #returns number of dimension of the array.

2

In [21]:
ar.size   #returns elements in the array

9

In [22]:
ar.nbytes  #Total bytes consumed by the array.

36

**1D Array Example **

In [23]:
box=np.array([1,20,44,919,79,101])    #Declaring a 1D Array

In [24]:
box

array([  1,  20,  44, 919,  79, 101])

In [25]:
box.argmax()  #returns index of the element with max value.

3

In [26]:
box.argmin()   #returns index of the element with min value.

0

In [27]:
box.argsort()    #returns the index of elements in Ascending Order.

array([0, 1, 2, 4, 5, 3], dtype=int64)

Taking Previous Example  i.e--->>>  '''ar''

In [28]:
ar

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [12, 24, 15]])

In [29]:
ar.argmin()  #returns index of the element with min value.

0

In [30]:
ar.argmax()   #returns index of the element with max value.

7

In [31]:
ar.argmax(axis=0)   #Returns max for columns.

array([2, 2, 2], dtype=int64)

In [32]:
ar.argmin(axis=0)    ##Returns min for columns.

array([0, 0, 0], dtype=int64)

In [33]:
ar.ravel()  #returns elements in List format.

array([ 1,  3,  5,  2,  4,  6, 12, 24, 15])

In [34]:
ar.reshape(9,1)  #reshapes the array.

array([[ 1],
       [ 3],
       [ 5],
       [ 2],
       [ 4],
       [ 6],
       [12],
       [24],
       [15]])

In [35]:
ar.reshape(9,)

array([ 1,  3,  5,  2,  4,  6, 12, 24, 15])

In [36]:
ar2=np.array([[ 1,  11,  7],
       [ 3,  1,  4],
       [2, 4, 1]])

In [37]:
ar2

array([[ 1, 11,  7],
       [ 3,  1,  4],
       [ 2,  4,  1]])

In [38]:
ar

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [12, 24, 15]])

In [39]:
ar + ar2

array([[ 2, 14, 12],
       [ 5,  5, 10],
       [14, 28, 16]])

In [40]:
ar*ar2

array([[ 1, 33, 35],
       [ 6,  4, 24],
       [24, 96, 15]])

In [41]:
np.sqrt(ar)

array([[1.        , 1.73205081, 2.23606798],
       [1.41421356, 2.        , 2.44948974],
       [3.46410162, 4.89897949, 3.87298335]])

In [42]:
np.sqrt(ar+ar2)

array([[1.41421356, 3.74165739, 3.46410162],
       [2.23606798, 2.23606798, 3.16227766],
       [3.74165739, 5.29150262, 4.        ]])

In [43]:
ar.sum()

72

In [44]:
ar.max()

24

In [45]:
ar.min()

1

In [46]:
(ar*ar2).max()   #Here when finding for 2 seperate arrays you have to give paranthesis() to get the right max/min value.

96

In [47]:
(ar+ar2).max()

28

In [48]:
ar2

array([[ 1, 11,  7],
       [ 3,  1,  4],
       [ 2,  4,  1]])

In [49]:
ar

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [12, 24, 15]])

In [58]:
np.count_nonzero(ar)

9

In [59]:
ar

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [12, 24, 15]])